hospitalProject/hospital/healthnet/urls.py
from . import views
from django.conf.urls import url

urlpatterns = (
    url(r'^$', views.LoginFormView.as_view(success_url="/healthnet/landing"), name='login-form'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^appointmentsJSON', views.send_appointments_as_JSON, name='JSON appointments'),
    url(r'^register/$', views.CreateAccountView.as_view(success_url="/healthnet"), name='create-account'),
    url(r'^register_doctor/$', views.CreateDoctorAccountView.as_view(success_url="/healthnet"),
        name='create-doctor-account'),
    url(r'^register_nurse/$', views.CreateNurseAccountView.as_view(success_url="/healthnet"),
        name='create-nurse-account'),
    url(r'^register_administrator/$', views.CreateAdministratorAccountView.as_view(success_url="/healthnet"),
        name='create-administrator-account'),
    url(r'^showcalendar/$', views.calendar_view, name='calendar'),
    url(r'^log/$', views.activity_log_view, name='activity-log'),
    url(r'^landing/$', views.landing_view, name='landing'),
    url(r'^appointment/$', views.CreateAppointmentView.as_view(success_url="/healthnet/landing"),
        name='create-appointment'),
    url(r'^appointment_employee/$', views.EmployeeCreateAppointmentView.as_view(success_url="/healthnet/landing"),
        name='employee-create-appointment'),
    url(r'^patientlist/$', views.activity_log_view, name='view-patient-list'),
    url(r'^profile_(?P<pk>[0-9]+)/edit/$', views.UpdateProfileView.as_view(success_url="/healthnet/landing"),
        name='update-profile'),
    url(r'^employee_(?P<pk>[0-9]+)/edit/$', views.UpdateEmployeeView.as_view(success_url="/healthnet/landing"),
        name='update-employee'),
    url(r'^profile_(?P<pk>[0-9]+)/$', views.ProfileDetailView.as_view(), name='profile-detail'),
    url(r'^employee_(?P<pk>[0-9]+)/$', views.EmployeeDetailView.as_view(), name='employee-detail'),
    url(r'^send/$', views.send_message, name="send message"),
    url(r'^message/$', views.message_index, name="message index"),

    url(r'^createdrug/$', views.CreateDrugView.as_view(success_url="/healthnet/createprescription"),
        name="create-drug"),
    url(r'^createcondition/$', views.CreateConditionView.as_view(success_url="/healthnet/landing"),
        name="create-condition"),
    url(r'^creatediagnosis/$', views.CreateDiagnosisView.as_view(success_url="/healthnet/landing"),
        name="create-diagnosis"),
    url(r'^createprescription/$', views.CreatePrescriptionView.as_view(success_url="/healthnet/landing"),
        name="create-prescription"),

    url(r'^list_appointments/$', views.list_appointments, name="verify appointment"),
    url(r'^verify/(?P<pk>[0-9]+)/$', views.confirm_appointment, name='verify appointment'),
    url(r'^list_appointments_delete/$', views.list_appointments_delete, name='delete appointment'),
    url(r'^confirm_delete/(?P<pk>[0-9]+)/$', views.DeleteAppointment.as_view(success_url="/healthnet/landing"),
        name='delete appointment'),
    url(r'^list_appointments_patient/$',views.list_appointments_patients,name='delete appointment patient'),
    url(r'^confirm_delete/(?P<pk>[0-9]+)/$',views.DeleteAppointment.as_view(success_url="/healthnet/landing"),
        name='delete appointment patient'),
    url(r'^update_Appointment/(?P<pk>[0-9]+)/$',views.update_Appointment,name='update appointment'),
    url(r'^update_appointment/$', views.update_appointment, name='update Appointment'),
    url(r'^update_Appointment_nurse/(?P<pk>[0-9]+)/$',views.update_Appointment_nurse,name='update appointment Nurse'),
    url(r'^update_appointment_nurse/$', views.update_appointment_nurse, name='update Appointment Nurse'),

    url(r'^statistics/$', views.StatisticsView, name='Statistics'),
    url(r'^medical_information_diagnosis/$', views.MedicalInformationDiagnosisView.as_view(),
        name='medical-information-diagnosis'),
    url(r'^medical_information_prescription/$', views.MedicalInformationPrescriptionView.as_view(),
        name='medical-information-prescription'),
    url(r'^medical_information_testresult/$', views.MedicalInformationTestResultView.as_view(),
        name='medical-information-testresult'),
    url(r'^deleteprescription/$', views.deleteprescription, name='list-prescriptions'),
    url(r'^confirm_delete_prescription/(?P<pk>[0-9]+)/$', views.DeletePrescription.as_view(success_url="/healthnet/landing"),
        name='delete-prescription'),
    url(r'^admit/([0-9]+)/([0-9]+)$', views.admit_patient_view, name='admit-patient'),
    url(r'^discharge/([0-9]+)/$', views.discharge_patient_view, name='discharge-patient'),
    url(r'^transfer/([0-9]+)/([0-9]+)$', views.transfer_patient_view, name='transfer-patient'),
    url(r'^access_denied', views.admit_patient_view, name='access-denied'),
    url(r'^create_test_results', views.CreateTestResultsView.as_view(success_url="/healthnet/landing"), name='create-test-results'),
    url(r'^all_patients_list/$', views.AllPatientListView.as_view(), name='view-patient-list'),
    url(r'^doctor_list/$', views.DoctorListView.as_view(), name='view-doctor-list')
)

hospitalProject/hospital/hospital/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^healthnet/', include('healthnet.urls')),
]

hospitalProject/hospital/healthnet/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.core.validators import RegexValidator, MinValueValidator

TEST_CHOICES = (
    ('PEN', 'Pending'),
    ('POS', 'Positive'),
    ('NEG', 'Negative'),
    ('INC', 'Inconclusive')
)
prescription_list = []
diagnosis_list = []


class Patient(User):
    class Meta:
        # Without this, the Patient class inherits the verbose name of the User.
        # This causes it to appear as "User" in the admin site.
        verbose_name = "Patient"

    insurance_plan = models.ForeignKey('InsurancePlan')
    date_of_birth = models.DateField(default=0)
    phone_number = models.CharField(max_length=10, validators=[
        RegexValidator('[0-9]{10}', "Must be 10 digits, numbers only")])
    contact_first_name = models.CharField(max_length=50, blank=True)
    contact_last_name = models.CharField(max_length=50, blank=True)
    contact_phone_number = models.CharField(max_length=10, blank=True, validators=[
        RegexValidator('[0-9]{10}|^$', "Must be 10 digits, numbers only")])
    doctor = models.ForeignKey('Doctor')
    admission = models.ForeignKey('Hospital',blank=True,default=None,null=True)

    def __repr__(self):
        return repr([self.first_name, self.last_name, self.username, self.password, self.email, self.insurance_plan,
                     self.date_of_birth, self.phone_number, self.emergency_contact])

    def role(self):
        return "patient"


class Employee(User):
    salary = models.IntegerField(validators=[MinValueValidator(0, "Must not be negative")])

    def role(self):
        return "admin"


class HospitalAdministrator(Employee):
    class Meta:
        # Without this, the HospitalAdministrator class inherits the verbose name of the User.
        # This causes it to appear as "User" in the admin site.
        verbose_name = "Hospital Administrator";

    hospital = models.ForeignKey('Hospital')

    def __repr__(self):
        return repr([self.first_name, self.last_name, self.username, self.password, self.email, self.salery,
                     self.hospital_name])


class Doctor(Employee):
    class Meta:
        # Without this, the Doctor class inherits the verbose name of the User.
        # This causes it to appear as "User" in the admin site.
        verbose_name = "Doctor"
        permissions = (("write_perscriptions", "Can write perscriptions for patients"),
                       ("give_diagnosis", "Can give a patient a diagnosis"))
    hospital = models.ForeignKey('hospital')

    def __repr__(self):
        return repr([self.first_name, self.last_name, self.username, self.email, self.salary])


class Nurse(Employee):
    class Meta:
        # Without this, the Nurse class inherits the verbose name of the User.
        # This causes it to appear as "User" in the admin site.
        verbose_name = "Nurse"

    def __repr__(self):
        return repr([self.first_name, self.last_name, self.username, self.password, self.email, self.salery])


class SuperAdmin(User):
    def __init__(self, first_name, last_name, password, username, email):
        SuperAdmin = User.objects.create_user(username=username, password=password, first_name=first_name,
                                              last_name=last_name, email=email, is_staff=True, is_superuser=True)
        SuperAdmin.save()

    def __repr__(self):
        return repr([self.first_name, self.last_name, self.username, self.password, self.email, self.role, self.salery])


class ScheduleItem(models.Model):
    start_time = models.DateTimeField('Appointment Time')
    end_time = models.DateTimeField('End Time')
    description = models.TextField(max_length=500)
    person = models.ForeignKey(Patient, default=None, related_name="my_events")
    doctor = models.ForeignKey(Doctor, default=None, related_name="doctor_list")
    verify = models.BooleanField(default=False, editable=True)
    accept_appointment = models.BooleanField(default=False, editable=True)

    def create_schedule(self, StartTime, EndTime, Description):
        schedule = self.create(start_time=StartTime, end_time=EndTime, description=Description)
        return schedule

    def __str__(self):
        return self.description


class Appointment(models.Model):
    patient_name = models.CharField(max_length=250)
    doctor_name = models.CharField(max_length=250)
    hospital = models.CharField(max_length=250)

    def create_appointment(self, PatientName, DoctorsName, Hospital):
        appointment = self.create(patient_name=PatientName, doctor_name=DoctorsName, hospital=Hospital)
        return appointment


class Hospital(models.Model):
    name = models.CharField(max_length=250)

    def create_hospital(self, HospitalName):
        hospital = self.create(name=HospitalName)
        return hospital


class InsurancePlan(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=500)


class LogItem(models.Model):
    time = models.DateTimeField()
    subject = models.CharField(default=None, null=True, max_length=50)
    action = models.IntegerField()
    actor = models.ForeignKey(User, default=None, null=True, related_name="actor")

    # def __init__(self, Time, Subject, ActionFlag, Actor = None):
    #     Item = super(LogItem,self).__init__(self,Time=Time, Subject=Subject, Action = LogItem.ActionDictionary[ActionFlag],Actor=Actor)
    #     Item.save(self)
    #     return Item

    def create_log_item(self, Actor, Action, Subject, Time):
        item = self.create(actor=Actor, action=Action, subject=Subject, time=Time)
        return item

    # post_init
    def action_string(self):
        action_dictionary = {0: 'CREATED', 1: 'EDITED', 2: 'DELETED', 3: 'LOGGED IN', 4: 'READ', 5: 'ADMITTED TO',
                             6: 'DISCHARGED FROM',}
        return action_dictionary.get(self.action)


class Message(models.Model):
    sender = models.ForeignKey(User, default=None, null=True, related_name="sender")
    receiver = models.ForeignKey(User, default=None, null=True, related_name="receiver")
    text = models.TextField(max_length=300)


class Condition(models.Model):
    condition_name = models.CharField(max_length=250)

    def create_conditon(self, condition_name):
        condition = self.create(condition_name=condition_name)
        return condition


class Drug(models.Model):
    drug_name = models.CharField(max_length=250)

    def create_drug(self, drug_name):
        drug = self.create(drug_name=drug_name)
        return drug


class Diagnosis(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    condition = models.ForeignKey(Condition, on_delete=models.CASCADE)
    date_of_diagnosis = models.DateField(default=0)
    doctors_notes = models.CharField(max_length=2500)

    def create_diagnosis(self, condition, patient, doctor, doctors_notes, date_of_diagnosis):
        diagnosis = self.create(condition=condition, patient=patient, doctor=doctor, date_of_diagnosis=date_of_diagnosis,
                                  doctors_notes=doctors_notes)
        return diagnosis


class Prescription(models.Model):
    drug = models.ForeignKey(Drug, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    doctors_notes = models.CharField(max_length=2500)
    date_prescribed = models.DateField(default=0)

    def create_prescription(self, drug, patient, doctor, doctors_notes, date_prescribed):
        prescription = self.create(drug=drug, patient=patient, doctor=doctor, date_prescribed=date_prescribed,
                                  doctors_notes=doctors_notes)
        return prescription


class TestResult(models.Model):
    name = models.CharField(max_length=200)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    date_of_test = models.DateField(default=0)
    results = models.CharField(max_length=3, choices=TEST_CHOICES)
    #test_file = models.FileField(upload_to="documents/")

    def create_test(self, name, patient, doctor, date_of_test, results):
        testresults = self.create(name=name, patient=patient, doctor=doctor, date_of_test=date_of_test,
                                  results=results)
        return testresults


class Statistic(models.Model):
    """
    Model for creating statistics
        statistic type: 0 = Prescriptions, 1 = Diagnosis, 2 = Average Length of Stay, 3 = Average Number of Vists Per
                        Patient, 4 = number of Patients Admitted to Hospital
        statistic value: The value that is of interest
        statistic string: For when the statistic needs a string associated with it
    """
    statistic_type = models.IntegerField()
    statistic_value = models.IntegerField()
    statistic_string = models.CharField(max_length=250)

hospitalProject/hospital/healthnet/templates/healthnet/patient_medical_information/medical_information_testresult.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Healthnet</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% load static %}
    <link href="{% static "assets/dashboard.css" %}" rel="stylesheet">
    <link rel='stylesheet' href="{% static 'fullcalendar.css' %}">
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'moment.min.js' %}"></script>
    <script src="{% static 'fullcalendar.js' %}"></script>
    <meta charset="UTF-8">

    <script>
    $(document).ready(function() {

    // page is now ready, initialize the calendar...

    $('#calendar').fullCalendar({
        // put your options and callbacks here
        defaultView: 'listWeek',
        events: '/healthnet/appointmentsJSON/'
    });
    });

    </script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">Welcome to HealthNet {{user.username}}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href={% url 'landing' %}>Dashboard</a></li>
            {% if role == "patient" %}
                <li><a href={% url 'profile-detail' pk=user.pk %}>Profile</a></li>
            {% else %}
                <li><a href={% url 'employee-detail' pk=user.pk %}>Profile</a></li>
            {% endif %}
            <li><a href="{% url 'logout_view' %}">Log Out</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href={% url 'landing' %}>Overview<span class="sr-only">(current)</span></a></li>
            <li><a href={% url 'calendar' %}>Calendar</a></li>
            {% if role == 'patient' %}
                <li><a href={% url 'create-appointment' %}>Create Appointment</a></li>
            {% else %}
                <li><a href = {% url 'employee-create-appointment' %}>Create Appointment</a></li>
            {% endif %}
            {% if role == "doctor" %}
                <li><a href = {% url 'verify appointment' %}>Verify/Update Appointment</a></li>
            {% endif %}
            {% if role == "patient" %}
                <li><a href = {% url 'update Appointment'%}>Update Appointment</a></li>
            {% endif %}
            {% if role == "nurse" %}
                <li><a href = {% url 'update Appointment Nurse'%}> Update Appointment</a></li>
            {% endif %}
            {% if role == "doctor" %}
                <li><a href = {% url 'delete appointment'%}>Delete Appointment</a></li>
            {% endif %}
            {% if role == "patient" %}
                <li><a href = {% url 'delete appointment patient'%}>Delete Appointment</a></li>
            {% endif %}
            <!-- <li><a href="#">Export</a></li> -->
          </ul>
          <ul class="nav nav-sidebar">
            {% if role == "patient" %}
                <li><a href = {% url 'medical-information-diagnosis' %}>View Past Diagnoses</a></li>
                <li><a href = {% url 'medical-information-prescription' %}>View Past Prescriptions</a></li>
                <li class="active"><a href = {% url 'medical-information-testresult' %}>View Past Test Results</a></li>
            {% endif %}
            {% if role == "doctor" or role == "nurse" or role == "superadmin" or role == "administrator" %}
                <li><a href = {% url 'view-patient-list' %}>All Registered Patients</a></li>
            {% endif %}
            {% if role == "doctor" or role == "superadmin" or role == "administrator" %}
                <li><a href = {% url 'view-doctor-list' %}>View Doctor List</a></li>
                <li><a href = {% url 'create-condition' %}>Add A New Condition</a></li>
                <li><a href = {% url 'create-drug' %}>Add A New Drug</a></li>
            {% endif %}
            {% if role == "doctor" %}
                <li><a href = {% url 'create-test-results' %}>Create Test Results</a></li>
                <li><a href = {% url 'create-diagnosis' %}>Create a Diagnosis</a></li>
                <li><a href = {% url 'create-prescription' %}>Create a Prescription</a></li>
                <li><a href = {% url 'list-prescriptions' %}>Delete Prescription</a></li>
            {% endif %}
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href={% url 'send message' %}>Send Message</a></li>
            <li><a href={% url 'message index' %}>View Inbox</a></li>
            <!-- <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li> -->
          </ul>
          <ul class="nav nav-sidebar">
            <!-- <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li> -->
            {% if role == "administrator" %}
                <li><a href={% url 'activity-log' %}>Activity Log</a></li>
                <li><a href={% url 'Statistics' %}>Statistics</a></li>
            {% endif %}
            {% if role == "administrator" or role == "superadmin" %}
                <li><a href = {% url 'create-nurse-account' %}>Create Nurse Account</a></li>
                <li><a href = {% url 'create-doctor-account' %}>Create Doctor Account</a></li>
                <li><a href = {% url 'create-administrator-account' %}>Create Administrator Account</a></li>
            {% endif %}
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Your Test Results</h1>
            <ul>
            {% for item in testresult_list %}
                <li> Test: {{item.name}} <br/> Doctor: {{item.doctor}}
                    <br/> Date Of Test: {{item.date_of_test}} <br/> Results: {{item.results}} <br/>
                    <a href="documents/"+"item.test_file") download>Official Test</a></li>
            {% endfor %}
            </ul>
        </div>
      </div>
    </div>
  </body>
</html>